### ISSUE TITLE
Fail to install cmake on Mac OSX

### ISSUE THREAD

**Issue by chvillanuevap** [hashdist/hashdist#332] opened 2015-04-30 13:07 UTC
This is my profile:
```
extends:
- file: osx_clt.yaml

parameters:
  PROLOGUE: |
    export CC=/Users/lindseybugbee/.hashdist/bld/gcc/7xwfonggow4t/bin/gcc; export CXX=/Users/lindseybugbee/.hashdist/bld/gcc/7xwfonggow4t/bin/g++; export FC=/Users/lindseybugbee/.hashdist/bld/gcc/7xwfonggow4t/bin/gfortran;

packages:
  launcher:
  blas:
    use: lapack
  lapack:
  mpi:
    use: openmpi
  trilinos:
  python:
    host: true
```
This the error from the CMake build log:
```
2015/04/30 06:18:28 - INFO: [package:run_job] /Users/lindseybugbee/.hashdist/bld/gcc/7xwfonggow4t/bin/g++  -I/Users/lindseybugbee/.hashdist/tmp/cmake-cvaiuryrreok-1/Bootstrap.cmk -I/Users/lindseybugbee/.hashdist/tmp/cmake-cvaiuryrreok-1/Source   -I/Users/lindseybugbee/.hashdist/tmp/cmake-cvaiuryrreok-1/Bootstrap.cmk -c /Users/lindseybugbee/.hashdist/tmp/cmake-cvaiuryrreok-1/Source/cmBootstrapCommands1.cxx -o cmBootstrapCommands1.o
2015/04/30 06:18:30 - INFO: [package:run_job] In file included from /usr/include/dispatch/dispatch.h:51:0,
2015/04/30 06:18:30 - INFO: [package:run_job]                  from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:15,
2015/04/30 06:18:30 - INFO: [package:run_job]                  from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFPropertyList.h:13,
2015/04/30 06:18:30 - INFO: [package:run_job]                  from /System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:55,
2015/04/30 06:18:30 - INFO: [package:run_job]                  from /Users/lindseybugbee/.hashdist/tmp/cmake-cvaiuryrreok-1/Source/cmFindProgramCommand.cxx:17,
2015/04/30 06:18:30 - INFO: [package:run_job]                  from /Users/lindseybugbee/.hashdist/tmp/cmake-cvaiuryrreok-1/Source/cmBootstrapCommands1.cxx:53:
2015/04/30 06:18:30 - INFO: [package:run_job] /usr/include/dispatch/object.h:143:15: error: expected unqualified-id before '^' token
2015/04/30 06:18:30 - INFO: [package:run_job]  typedef void (^dispatch_block_t)(void);
2015/04/30 06:18:30 - INFO: [package:run_job]                ^
2015/04/30 06:18:30 - INFO: [package:run_job] /usr/include/dispatch/object.h:143:15: error: expected ')' before '^' token
2015/04/30 06:18:30 - INFO: [package:run_job] /usr/include/dispatch/object.h:362:3: error: 'dispatch_block_t' has not been declared
2015/04/30 06:18:30 - INFO: [package:run_job]    dispatch_block_t notification_block);
2015/04/30 06:18:30 - INFO: [package:run_job]    ^
2015/04/30 06:18:31 - INFO: [package:run_job] make: *** [cmBootstrapCommands1.o] Error 1
2015/04/30 06:18:31 - INFO: [package:run_job] ---------------------------------------------
2015/04/30 06:18:31 - INFO: [package:run_job] Error when bootstrapping CMake:
2015/04/30 06:18:31 - INFO: [package:run_job] Problem while running make
2015/04/30 06:18:31 - INFO: [package:run_job] ---------------------------------------------
2015/04/30 06:18:31 - INFO: [package:run_job] Log of errors: /Users/lindseybugbee/.hashdist/tmp/cmake-cvaiuryrreok-1/Bootstrap.cmk/cmake_bootstrap.log
2015/04/30 06:18:31 - INFO: [package:run_job] ---------------------------------------------
2015/04/30 06:18:31 - ERROR: [package:run_job] Command '[u'/bin/bash', '_hashdist/build.sh']' returned non-zero exit status 9
2015/04/30 06:18:31 - ERROR: [package:run_job] command failed (code=9); raising
```
I also tried using Homebrew's GCC, but got the same error again.

I also tried using CMake 3.2.2, along with Homebrew's formula but again, no success.

**Comment by certik** [comment] 2015-04-30 15:03
This one is caused by the fact, that OS X 10.10 ships Object C stuff in a C header file.... See this patch that fixes it: https://github.com/hashdist/hashstack/issues/727#issuecomment-92981618, i.e. the line:
```
sed 's+typedef void (\^dispatch_block_t)(void)+typedef void* dispatch_block_t+' /usr/include/dispatch/object.h > "$ARTIFACT/include/dispatch/object.h"
```
It looks like an OS X 10.10 bug, we just need to figure out a workaround.

**Comment by certik** [comment] 2015-04-30 15:04
I think the work around is to ship this fixed header file with out own gcc and make sure it is used instead of the system one.

**Comment by chvillanuevap** [comment] 2015-04-30 15:30
For now, should I just place that in the PROLOGUE?

**Comment by certik** [comment] 2015-04-30 16:14
Try anything that will fix it. I don't know if there is any way to force the systemwide gcc to look into your place with the fixed header file first.

**Comment by chvillanuevap** [comment] 2015-04-30 17:47
I found this answer on StackOverflow:

http://stackoverflow.com/questions/27976312/how-to-cope-with-non-gcc-compatible-code-in-os-x-yosemite-core-headers

It seems GCC is no longer supported on OSX, so I can only assume these sort of issues will get worse over time.

I'll attempt to build CMake with clang.

**Comment by certik** [comment] 2015-04-30 19:18
I think that the system wide header files are not supported by gcc, but that means that we need to install our own gcc and make it use our own header files. Then there is no problem.

**Comment by chvillanuevap** [comment] 2015-04-30 19:19
I set the CC, CXX, and FC variables to the HashDist GCC in the PROLOGUE.

What else is needed to use our own header files?

**Comment by certik** [comment] 2015-04-30 19:53
Does it work? If so, then that should do it. If it doesn't work, then gcc is still using the systemwide header files, in which case we need to investigate how to force it not to use them.

**Comment by chvillanuevap** [comment] 2015-04-30 19:55
It didn't work. I tried setting those variables to HashDist's GCC built with Homebrew's GCC, and to Homebrew's GCC.

**Comment by certik** [comment] 2015-04-30 20:20
Ok, thanks for trying it. I took this patch from https://github.com/sagemath/sage/blob/f0f7b3a1b3b68688610cef5d131ae696f3034c7b/build/pkgs/gcc/spkg-install#L73. In there, they copy the fixed include file into their universal prefix. In our case, we need to put it at some place where gcc will find it. 

This will require some trial and error. What you can do is put the fixed header file manually (to avoid lengthy gcc rebuild) into `~/.hashdist/bld/gcc/##proper_hash##/include/` or perhaps into `~/.hashdist/bld/gcc/##proper_hash##/include/c++/4.9.2/` and see if it fixes it. If it does, we can think how to patch our gcc build to do this properly. If it doesn't, let me know, we'll try other things.

**Comment by chvillanuevap** [comment] 2015-05-01 01:33
I was able to build CMake with clang.

**Comment by certik** [comment] 2015-05-01 17:59
https://github.com/hashdist/hashstack/commit/aa41e3b743adff7e54673472547385c2f185fa43 should fix this (it's part of https://github.com/hashdist/hashstack/pull/743).

**Closed** 2015-05-07 00:53 UTC
